### PR TITLE
Add a license badge to README

### PR DESCRIPTION
**Pull request by cgrigel**
Added new badges, fixed grammar in README.MD #hacktoberfest

### CODE REVIEW

**Comment by cgrigel** [comment]
Added new badges, fixed grammar in README.MD #hacktoberfest

**Comment by daniel-beck** [comment]
What's the point of these badges? The information they show is already shown elsewhere on the repository index. They link to pages already linked elsewhere on the same page. What am I missing?

**Comment by cgrigel** [comment]
Dear @daniel-beck,

I Understand your point, my bad. 
I just used suggested badged for this project generated via shield.io and deficiently verify them enough.

**Comment by daniel-beck** [comment]
@cgrigel Thanks for your response!

Please note I am not a maintainer of this particular component, so the determination whether this adds enough value to get merged is up to someone else. I was simply confused about the specific badges you added.

**Comment by cgrigel** [comment]
Dear @daniel-beck,
Anyway thanks for your feedback.
I will retrieve this if no one approves this PR or provides additional feedback to the passage of time.

**Comment by cgrigel** [comment]
@oleg-nenashev thank you for your concern, I  removed unnecessary badges and left only the license badge.

**Comment by oleg-nenashev** [comment]
Thanks!

**Comment by daniel-beck** [comment]
> Adding a license badge makes sense IMHO.

Not any less redundant than the other badges would be.

Screenshot

**Pull request merged**
