### PR TITLE
Upgrade the Surefire plugin.

### PR DESCRIPTION
**Pull request by antoinell**
Otherwise the SUREFIRE-1541 issue :
  SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
happens when building the amazon-ecs-plugin with
- Maven 3.5.2
- openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

### CODE REVIEW

**Comment by antoinell** [comment]
Hello Oleg,
is there something missing here or can you accept this pull request ?
Antoine

**Comment by antoinell** [comment]
I forgot to add that I force pushed to the pull request branch so there is only one commit in the history on the pull request.

**Comment by oleg-nenashev** [comment]
Moreover there is no email notifications on force-pushes 🤷‍♂️

**Comment by oleg-nenashev** [comment]
sry, sisn't plan to close it

**Comment by antoinell** [comment]
Is there somewhere a continuous integration system which tests the impact of the change on all plugins ? That continuous integration system would need to simulate the upgrade of the parent POM version to the output coming from this pull request and run all the builds/tests/integration tests.

**Comment by jglick** [comment]
> Is there somewhere a continuous integration system which tests the impact of the change on all plugins ?

No, that would take days to run, and many plugins would fail such an upgrade anyway.

There is a `src/it/` directory here which tests some common issues.

**Comment by batmat** [comment]
@antoinell I just deployed a SNAPSHOT for your PR. 
Version is `3.33-20190110.101436-2` for the sha `2717afd28cbd7124efa2f541074cfe285fced037`.

**Comment by antoinell** [comment]
Thanks @batmat I created this PR jenkinsci/git-plugin#655 to test the actual build. @jglick sorry I did not push the upgrade to M3 yet.

**Comment by antoinell** [comment]
I did a rebase where I rewrote other people's commits. Let me close this PR and create a new one.

**Pull request closed without merging**
