### PR TITLE
Support a SpotBugs exclude filter file for Maven multi-module projects

### PR DESCRIPTION
**Pull request by basil**
Like https://github.com/jenkinsci/pom/pull/337 but for `plugin-pom`. I tested this logic as part of the other PR.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by NotMyFault — APPROVED** [review]

**Comment by jtnord** [comment]
What was the rationale here, the filter already worked for multi-module projects - you just put the the exclude file alongside your modules projects which ?

Additionally the directory used will seem to be incorrect if you have an aggregator project to build multiple other projects (that are not in the same github repo - e,g. using submodules, [or extra clones](https://github.com/cloudbees/operations-center-all)).

Additionally why would someone not want to have their exclude file in the location with their module (which it corresponds to ) as opposed to a higher level?

e.g. 
https://github.com/cloudbees/cloudbees-cyberark-credentials-plugin/blob/master/cyberark-aim-stub/src/spotbugs/excludesFilter.xml shows this was working before and thus no change should have been required.

**Comment by amuniz** [comment]
Agree. This inconvenient and possibly breaking some of our builds.

**Comment by basil** [comment]
Do you have a link to a consumer in the `jenkinsci` GitHub organization that is broken by this change?

**Comment by basil** [comment]
I did a corpus study of the repositories in `jenkinsci` with a multi-module build and a SpotBugs excludes file. It turned out that in most cases they were not really benefiting from a centralized exclusion file, and most of the exclusions applied only to one module in the multi-module build. In light of this and the downsides mentioned above, I will revert this change.

**Comment by basil** [comment]
Thanks for bringing this to my attention James. I released POM 1.92 and plugin POM 4.51 with `project.basedir` and filed the following PRs to adapt consumers:

- https://github.com/jenkinsci/jenkins/pull/7422
- https://github.com/jenkinsci/lib-access-modifier/pull/125
- https://github.com/jenkinsci/stapler/pull/418
- https://github.com/jenkinsci/swarm-plugin/pull/505

I think the result turned out nicely with the exclusion logic living closer to the code being excluded, resulting in improved readability.

**Comment by amuniz** [comment]
Thanks Basil.

**Pull request merged**
