### PR TITLE
[JENKINS-57425] Add profile to run benchmarks only when the `benchmark` property is set

### PR DESCRIPTION
**Pull request by AbhyudayaSharma**
Adds a profile to run JMH benchmarks only when the `benchmark` property is set. Follow-up to https://github.com/jenkinsci/jenkins-test-harness/pull/135 .

@jenkinsci/gsoc2019-role-strategy

### CODE REVIEW

**Comment by AbhyudayaSharma** [comment]
Another unreleated build failure 🤔:
```
Failed to run image 'maven:3.6.0-jdk-8'. Error: docker: Error response from daemon: mkdir /var/lib/docker/overlay2/b5073d410ec3435d970b02bd8eca4768dca47542a46270394ec65a960b2ed6e0-init: no space left on device.
```

**Comment by casz** [comment]
https://issues.jenkins-ci.org/plugins/servlet/mobile#issue/INFRA-2062 a ongoing issue

**Comment by AbhyudayaSharma** [comment]
@casz Thanks for the information!

**Comment by AbhyudayaSharma** [comment]
> Looks good to me as code, but it would be also great to have documentation and maybe a short integration test in src/it

@oleg-nenashev Where do I add the integration test inside `src/it`? The existing folders are confusing. Do I use them or do I create a new folder for this?

**Comment by AbhyudayaSharma** [comment]
The build fails because incrementals need to be enabled with `-Pconsume-incrementals`:
```
[2019-06-11T05:01:49.141Z] [ERROR] Failed to execute goal on project plugin: Could not resolve dependencies for project org.jenkins-ci.plugins:plugin:pom:3.44-SNAPSHOT: Could not find artifact org.jenkins-ci.main:jenkins-test-harness:jar:2.50-rc1168.d591189fccf7 in repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/) -> [Help 1]
```

**Comment by oleg-nenashev** [comment]
I am going to merge and release it to unblock further integration of changes by @AbhyudayaSharma . All the code is isolated by the profile (no default behavior change) and has integration tests, so it should be fine.

@batmat @jglick I will address any follow-up requests if needed

**Pull request merged**
