### PR TITLE
Move node/npm download root to properties to allow easy override

### PR DESCRIPTION
**Pull request by Vlatombe**
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Review by jtnord — APPROVED** [review]

**Review by amuniz — APPROVED** [review]

**Review by dwnusbaum — APPROVED** [review]
Are the current URLs are broken for any OSS plugins that are using `frontend-maven-plugin`? Should we update them to something else?

**Comment by Vlatombe** [comment]
OSS infrastructure is flaky since some jfrog saas update apparently, and ideally in CloudBees we'd like to use a different mirror to avoid pegging the OSS infrastructure.

**Comment by timja** [comment]
Is there any context to the why of this PR?

i.e. why does this need changing?

**Comment by dwnusbaum** [comment]
> OSS infrastructure is flaky

Ah, ok, I thought that these URLs were failing consistently. When I checked locally with curl, it looked like the problem was that the download links created by `frontend-maven-plugin` actually hit a page that requires JavaScript to initiate the download, but maybe that's not always the case.

**Comment by timja** [comment]
> > OSS infrastructure is flaky
> 
> Ah, ok, I thought that these URLs were failing consistently. When I checked locally with curl, it looked like the problem was that the download links created by `frontend-maven-plugin` actually downloaded an HTML page that would run JavaScript to initiate the download if you were using a web browser, but maybe that's not always the case.

they are doing user agent sniffing, it's really annoying.

curl should get actual files, but powershell does not.
We had to change the jenkins docker images to pretend to be curl so that our windows agent images could fetch remoting.

**Comment by jtnord** [comment]
I can not deploy this at the moment despite using my reset password.  not sure if it is something for my account or more generally that deployments are still not working.

**Comment by jtnord** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/2079

**Comment by Vlatombe** [comment]
@jtnord you should have permission now.

**Comment by jglick** [comment]
Or if you want me to cut a release, just LMK.

I have not yet tried to set this repo up for JEP-229 or even JEP-305 out of concern that https://www.mojohaus.org/flatten-maven-plugin/flatten-mojo.html#flattenMode is not configured correctly for the POM use case. It does work fine on `bom` so it is probably safe here too but needs some careful testing.

**Pull request merged**
