### PR TITLE
[JENKINS-24064] Do not use war-for-test

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/43; complements https://github.com/jenkinsci/jenkins/pull/2634.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
CI failure is just that the job did not seem to pick up the snapshot artifact I deployed.

**Comment by jglick** [comment]
Tested against a few plugins, using both the current baseline and a core snapshot from https://github.com/jenkinsci/jenkins/pull/2634, without finding any more problems, so I think this is ready for review.

**Comment by stephenc** [comment]
Something like

```
<component>
  <role>org.apache.maven.artifact.handler.ArtifactHandler</role>
  <role-hint>executable-war</role-hint>
  <implementation>
    org.apache.maven.artifact.handler.DefaultArtifactHandler
  </implementation>
  <configuration>
    <type>executable-war<;/type>
    <extension>war</extension>
    <language>java</language>
    <addedToClasspath>true</addedToClasspath>
  </configuration>
</component>
```

We might not even need to modify the war build as its only when declaring a dependency that this would be used, so it may be that the above registered as an extension is all we require

**Comment by jglick** [comment]
Sounds promising. I do not understand the full implications, in particular whether this would allow a single parent POM configuration to work correctly before or after the switch. IIUC changes to `jenkinsci/jenkins` then become unnecessary?

**Comment by stephenc** [comment]
>  allow a single parent POM configuration to work correctly before or after the switch

Should allow it as you already have the .war deployed (assuming the tests work in resolving the war from the classpath)

**Comment by jglick** [comment]
> IDEs should set up the in-IDE test execution classpath correctly without needing the generate-test-resources phase execution (saving disk space of copying the war file into everyone's target/test-classes

I am not sure what this was referring to. Nothing copies a WAR into `target/test-classes/` that I can find. There is `WarExploder`, which unpacks the WAR into `target/jenkins-for-test/` (perhaps unnecessarily—the `WebAppContext` constructor does claim to support a packed WAR file), but this is just picking up `jenkins-war-*-war-for-test.jar` currently and would begin picking up `jenkins-war-*.war` instead if the test classpath were changed according to your proposal.

**Comment by jglick** [comment]
Oh I see, you are talking about the `dependency:copy` proposed in this PR.

**Comment by jglick** [comment]
It works!

**Pull request closed without merging**
