### PR TITLE
update test-harness

### PR DESCRIPTION
**Pull request by Pldi23**
test-harness 1802.v9de0d87365d2 contain important update to remove test flakiness (via htmlunit update)

### CODE REVIEW

**Comment by jetersen** [comment]
I'd suggest waiting for dependabot to bump or ask someone nicely to force dependabot to check by going here: https://github.com/jenkinsci/plugin-pom/network/updates

image
image

**Comment by jetersen** [comment]
I see someone read my comment: https://github.com/jenkinsci/plugin-pom/pull/571 😉

**Comment by Pldi23** [comment]
closed because of #571

**Comment by timja** [comment]
> I see someone read my comment: #571 😉

hehe was me :)

**Pull request closed without merging**
