### PR TITLE
Prepare CD via MRP

### PR DESCRIPTION
**Pull request by jglick**
https://github.com/jenkins-infra/repository-permissions-updater/pull/2223 using https://github.com/jenkins-infra/jenkins-maven-cd-action/pull/14. I hope it works.

### CODE REVIEW

**Comment by jtnord** [comment]
does this not require a corresponding change in the `pom.xml`?

**Review by jtnord — COMMENTED** [review]
I am completely confused here why we want to run MRP in a cd fashion with no changes with pushChanges and the like.  Discussion on Dec list makes it no clearer to me.

**Comment by jglick** [comment]
> why we want to run MRP in a cd fashion

Merely to make it easier to cut release by pushing a button (or, perhaps, just merging an appropriately labeled PR) without making any other process changes so far, and without requiring local developer credentials.

**Comment by jglick** [comment]
#627 should not be controversial, and I would rather just enable JEP-229 here after that is merged than mess around with MRP. https://github.com/jenkinsci/plugin-pom/pull/627#discussion_r1013050114 but we are already [treating the version number as opaque](https://groups.google.com/g/jenkinsci-dev/c/LLN4RdRxiJo/m/G4PlbA3sAAAJ) so :shrug:

**Pull request closed without merging**
