### PR TITLE
Enforce English Locale for JavaDoc Generation

### PR DESCRIPTION
**Pull request by XiongKezhi**
Ref: http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#locale

cc @timja @oleg-nenashev

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Background: When Kezhi releases plugins the JavaDoc comes out in Chinese.

**Comment by XiongKezhi** [comment]
> Background: When Kezhi releases plugins the JavaDoc comes out in Chinese.

yes, example: https://javadoc.jenkins.io/plugin/checks-api/

**Review by jetersen — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Would be great to also add it to https://github.com/jenkinsci/pom

**Comment by timja** [comment]
@oleg-nenashev you planning to release this or shall I?

**Comment by jetersen** [comment]
https://github.com/jenkinsci/pom/pull/137

**Comment by oleg-nenashev** [comment]
@timja If there is an interest to have the release now, go ahead. If not, I would prefer to pick up Maven HPI Plugin and Jenkins Test Harness updates. https://github.com/jenkinsci/maven-hpi-plugin/pull/191 from @Vlatombe looks quite important to be reviewed

**Comment by timja** [comment]
I'll release now

**Pull request merged**
