### PR TITLE
[FIX INFRA-588] Using the right repo URL

### PR DESCRIPTION
**Pull request by batmat**
Ping @abayer @daniel-beck @rtyler @andresrc @jglick

### CODE REVIEW

**Comment by batmat** [comment]
By the way, why wouldn't we inherit directly from the Jenkins organization pom?

That would reduce the copy-paste here, while still not being tied a Jenkins core version, that being one of the most important driver of this having been externalized.

**Comment by andresrc** [comment]
:+1: but shouldn't we change the download repos to `https` as well, as in https://github.com/jenkinsci/pom/commit/14b50c0812582838c63af5fceac5b34d160e196d?

Regarding inheriting from the org pom to get it from there, well, infra stuff doesn't change that often, and you'll get a lot other stuff, so I wouldn't do it right now.

Thanks!

**Comment by batmat** [comment]
Absolutely @andresrc would make sense. In this PR I _only_ wanted to fix the wrong ones (outdated and already failing in many situations). 

But also going from http -> https may be better, and also more consistent indeed. Gonna add one commit about that.

**Comment by batmat** [comment]
Added @andresrc thanks for the review.

**Comment by andresrc** [comment]
@batmat thank you!

**Comment by batmat** [comment]
:wink:

**Pull request merged**
