### PR TITLE
Configurable frontend plugin version

### PR DESCRIPTION
**Pull request by tfennelly**
And fix to windows paths for x64 and x86

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Not sure I understand it, but :bee:

**Comment by recena** [comment]
:bee:

**Comment by tfennelly** [comment]
@jglick Sorry, I should have added more detail.  Fixes 2 issues...

1. The frontend plugin was stuck on an older version and there was no way of updating it without changing the parent pom, hence we made that configurable for future.
1. The windows profiles for selecting the download folder name were wrong + there was some redundant stuff in there.

**Comment by recena** [comment]
@tfennelly In fact, Jenkins core is using `1.0`, [ref](https://github.com/jenkinsci/jenkins/blob/master/war/pom.xml#L707).

**Comment by tfennelly** [comment]
@recena cool, thanks

**Pull request merged**
