### PR TITLE
Bump jenkins test harness to 2.66

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/jenkins-test-harness/releases/tag/jenkins-test-harness-2.66

<details>
<summary>Release notes</summary>

> ## 📦 Dependency updates
> 
> * Bump jenkins-test-harness-htmlunit from 2.36.0-1 to 3 (#232) @dependabot
> * Bump jetty.version from 9.4.30.v20200611 to 9.4.31.v20200723 (#231) @dependabot

</details>

### CODE REVIEW

**Comment by timja** [comment]
Releasing

**Comment by timja** [comment]
Lol at 4 minutes ago release without this 👅 https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.5

**Comment by jetersen** [comment]
Just do yet another release 👍

**Comment by timja** [comment]
done

**Comment by jglick** [comment]
Sorry, too much stuff in flight! Thanks for handling this.

**Pull request merged**
