### PR TITLE
Removing SUREFIRE-1588 workaround now that jdk.net.URLClassPath.disableClassPathURLCheck=true is the default

### PR DESCRIPTION
**Pull request by jglick**
Cleans up #131. [Discussion](https://issues.apache.org/jira/browse/SUREFIRE-1588?focusedCommentId=16704836&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16704836)

### CODE REVIEW

**Comment by jglick** [comment]
Hmm, https://hub.docker.com/r/library/maven/ `3.6.0-jdk8` is not tracking upstream updates well: https://github.com/carlossg/docker-maven/issues/90

**Comment by jglick** [comment]
On hold pending some assistance from @carlossg on the Maven Docker images.

**Comment by batmat** [comment]
@jglick what about https://issues.apache.org/jira/browse/SUREFIRE-1588?focusedCommentId=16704866&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16704866 ?

**Comment by jglick** [comment]
Maybe premature.

**Comment by jglick** [comment]
FTR besides https://github.com/jenkinsci/jenkins/pull/3782 & https://github.com/jenkinsci/pom/pull/35 there was also https://github.com/jenkinsci/jenkins-test-harness/blob/278b71ad903a7151b9f0f45585995d03b67bf15f/pom.xml#L186 + https://github.com/jenkinsci/acceptance-test-harness/blob/527220a8bd70c9194fc938ad7b1957d1e8e7d911/pom.xml#L491 that I know of.

**Pull request closed without merging**
